version: "3.7"
services:
  app:
    image: app
    container_name: app
    build:
      context: ./apps/app
      dockerfile: Dockerfile-api
    restart: always
    working_dir: /var/www/
    depends_on:
      - postgresql
    volumes:
      - ./apps/app/:/var/www
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - dev-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./apps/app/:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - dev-network


  postgresql:
    image: postgres:latest
    container_name: postgresql
    tty: true
    ports:
      - 54320:5432
    environment:
      POSTGRES_DB: postgresql
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: Acesso123
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    networks:
      - dev-network
    restart: unless-stopped

networks:
  dev-network:
    driver: bridge
